name = "gasoia-worker"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "gasoia-db"
database_id = "5e4221ca-69e4-4c71-bf21-154395364b1f"

[vars]
ADSENSE_PUBLISHER_ID = ""
SITE_URL = "https://gasoia.com"

[env.production]
name = "gasoia-worker"

  [env.production.vars]
  SITE_URL = "https://gasoia.com"
